### ISSUE TITLE
/book/search Pagination

### ISSUE THREAD

**Issue by AdamMcAdamson** [AdamMcAdamson/Cs4347.002-Helium#27]
Right now, we return the first X number of books that match the query. We probably want to enable full pagination. 
It might be easiest to implement with the [limit/offset SQL clauses](https://www.sqltutorial.org/sql-limit/).

If we go that route:
 - [x] Implement Limit/Offset Pagination
 - [x] Add offset query parameter

**Comment by KryptonC-02** [comment]
search class modified to facilitate, only major change is that it needs to be passed a page number to determine the offset.
Couldn't find where to take it from there, as I couldn't figure out where the class methods were called.

**Comment by AdamMcAdamson** [comment]
All that is left is to Implement is a way for the frontend to navigate to the Next/Prev/X page, should there be one.
