### ISSUE TITLE
B3b: [GET] /book/search endpoint

### ISSUE THREAD

**Issue by AdamMcAdamson** [AdamMcAdamson/Cs4347.002-Helium#5]
[GET] /book/search endpoint (Frontend Dependency)

 - [x] Search for book by ISBN, title, and/ or Author(s)
 - [x] Handle queries from a single text search field and be case insensitive.
 - [x] Substring matching

**Comment by PureAsbestos** [comment]
see #24

**Comment by PureAsbestos** [comment]
Needs to get the book availability still, though, once that is added to the DB. And proper paging, right now it just returns the first 20. Should probably make a new issue for that
